// Generated by gencpp from file action_server/ControlJointsFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_MESSAGE_CONTROLJOINTSFEEDBACK_H
#define ACTION_SERVER_MESSAGE_CONTROLJOINTSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_server
{
template <class ContainerAllocator>
struct ControlJointsFeedback_
{
  typedef ControlJointsFeedback_<ContainerAllocator> Type;

  ControlJointsFeedback_()
    {
    }
  ControlJointsFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::action_server::ControlJointsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_server::ControlJointsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ControlJointsFeedback_

typedef ::action_server::ControlJointsFeedback_<std::allocator<void> > ControlJointsFeedback;

typedef boost::shared_ptr< ::action_server::ControlJointsFeedback > ControlJointsFeedbackPtr;
typedef boost::shared_ptr< ::action_server::ControlJointsFeedback const> ControlJointsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_server::ControlJointsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_server::ControlJointsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace action_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_server::ControlJointsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server::ControlJointsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::ControlJointsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::action_server::ControlJointsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_server/ControlJointsFeedback";
  }

  static const char* value(const ::action_server::ControlJointsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback (optional)\n"
"# You can include feedback fields here if needed\n"
"\n"
"\n"
;
  }

  static const char* value(const ::action_server::ControlJointsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlJointsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_server::ControlJointsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::action_server::ControlJointsFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_SERVER_MESSAGE_CONTROLJOINTSFEEDBACK_H
