// Generated by gencpp from file action_server/MoveToPoseFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_MESSAGE_MOVETOPOSEFEEDBACK_H
#define ACTION_SERVER_MESSAGE_MOVETOPOSEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_server
{
template <class ContainerAllocator>
struct MoveToPoseFeedback_
{
  typedef MoveToPoseFeedback_<ContainerAllocator> Type;

  MoveToPoseFeedback_()
    : feedback(0.0)  {
    }
  MoveToPoseFeedback_(const ContainerAllocator& _alloc)
    : feedback(0.0)  {
  (void)_alloc;
    }



   typedef float _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::action_server::MoveToPoseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_server::MoveToPoseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPoseFeedback_

typedef ::action_server::MoveToPoseFeedback_<std::allocator<void> > MoveToPoseFeedback;

typedef boost::shared_ptr< ::action_server::MoveToPoseFeedback > MoveToPoseFeedbackPtr;
typedef boost::shared_ptr< ::action_server::MoveToPoseFeedback const> MoveToPoseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_server::MoveToPoseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_server::MoveToPoseFeedback_<ContainerAllocator1> & lhs, const ::action_server::MoveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_server::MoveToPoseFeedback_<ContainerAllocator1> & lhs, const ::action_server::MoveToPoseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_server::MoveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server::MoveToPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::MoveToPoseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d90953f904aa7b8e8d8b4f90a196f18f";
  }

  static const char* value(const ::action_server::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd90953f904aa7b8eULL;
  static const uint64_t static_value2 = 0x8d8b4f90a196f18fULL;
};

template<class ContainerAllocator>
struct DataType< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_server/MoveToPoseFeedback";
  }

  static const char* value(const ::action_server::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback (optional)\n"
"float32 feedback\n"
"\n"
"\n"
;
  }

  static const char* value(const ::action_server::MoveToPoseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPoseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_server::MoveToPoseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_server::MoveToPoseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<float>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_SERVER_MESSAGE_MOVETOPOSEFEEDBACK_H
