; Auto-generated. Do not edit!


(cl:in-package action_server-msg)


;//! \htmlinclude ControlJointsResult.msg.html

(cl:defclass <ControlJointsResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ControlJointsResult (<ControlJointsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ControlJointsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ControlJointsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_server-msg:<ControlJointsResult> is deprecated: use action_server-msg:ControlJointsResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <ControlJointsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server-msg:success-val is deprecated.  Use action_server-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ControlJointsResult>) ostream)
  "Serializes a message object of type '<ControlJointsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ControlJointsResult>) istream)
  "Deserializes a message object of type '<ControlJointsResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ControlJointsResult>)))
  "Returns string type for a message object of type '<ControlJointsResult>"
  "action_server/ControlJointsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ControlJointsResult)))
  "Returns string type for a message object of type 'ControlJointsResult"
  "action_server/ControlJointsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ControlJointsResult>)))
  "Returns md5sum for a message object of type '<ControlJointsResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ControlJointsResult)))
  "Returns md5sum for a message object of type 'ControlJointsResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ControlJointsResult>)))
  "Returns full string definition for message of type '<ControlJointsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Response part (Result)~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ControlJointsResult)))
  "Returns full string definition for message of type 'ControlJointsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Response part (Result)~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ControlJointsResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ControlJointsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ControlJointsResult
    (cl:cons ':success (success msg))
))
