; Auto-generated. Do not edit!


(cl:in-package action_server-msg)


;//! \htmlinclude ControlJointsActionGoal.msg.html

(cl:defclass <ControlJointsActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type action_server-msg:ControlJointsGoal
    :initform (cl:make-instance 'action_server-msg:ControlJointsGoal)))
)

(cl:defclass ControlJointsActionGoal (<ControlJointsActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ControlJointsActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ControlJointsActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_server-msg:<ControlJointsActionGoal> is deprecated: use action_server-msg:ControlJointsActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <ControlJointsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server-msg:header-val is deprecated.  Use action_server-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <ControlJointsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server-msg:goal_id-val is deprecated.  Use action_server-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <ControlJointsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server-msg:goal-val is deprecated.  Use action_server-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ControlJointsActionGoal>) ostream)
  "Serializes a message object of type '<ControlJointsActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ControlJointsActionGoal>) istream)
  "Deserializes a message object of type '<ControlJointsActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ControlJointsActionGoal>)))
  "Returns string type for a message object of type '<ControlJointsActionGoal>"
  "action_server/ControlJointsActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ControlJointsActionGoal)))
  "Returns string type for a message object of type 'ControlJointsActionGoal"
  "action_server/ControlJointsActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ControlJointsActionGoal>)))
  "Returns md5sum for a message object of type '<ControlJointsActionGoal>"
  "18bfb6c42ebe9d2a39038d529ae07e04")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ControlJointsActionGoal)))
  "Returns md5sum for a message object of type 'ControlJointsActionGoal"
  "18bfb6c42ebe9d2a39038d529ae07e04")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ControlJointsActionGoal>)))
  "Returns full string definition for message of type '<ControlJointsActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ControlJointsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: action_server/ControlJointsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Request part (Goal)~%float64 torso_lift~%float64 arm_1~%float64 arm_2~%float64 arm_3~%float64 arm_4~%float64 arm_5~%float64 arm_6~%float64 arm_7~%float64 gripper_position  # 0.0 for open, 1.0 for close (or adjust as needed)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ControlJointsActionGoal)))
  "Returns full string definition for message of type 'ControlJointsActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ControlJointsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: action_server/ControlJointsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Request part (Goal)~%float64 torso_lift~%float64 arm_1~%float64 arm_2~%float64 arm_3~%float64 arm_4~%float64 arm_5~%float64 arm_6~%float64 arm_7~%float64 gripper_position  # 0.0 for open, 1.0 for close (or adjust as needed)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ControlJointsActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ControlJointsActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ControlJointsActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
