; Auto-generated. Do not edit!


(cl:in-package action_server-msg)


;//! \htmlinclude MoveToPoseFeedback.msg.html

(cl:defclass <MoveToPoseFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveToPoseFeedback (<MoveToPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_server-msg:<MoveToPoseFeedback> is deprecated: use action_server-msg:MoveToPoseFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <MoveToPoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_server-msg:feedback-val is deprecated.  Use action_server-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToPoseFeedback>) ostream)
  "Serializes a message object of type '<MoveToPoseFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToPoseFeedback>) istream)
  "Deserializes a message object of type '<MoveToPoseFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'feedback) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToPoseFeedback>)))
  "Returns string type for a message object of type '<MoveToPoseFeedback>"
  "action_server/MoveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToPoseFeedback)))
  "Returns string type for a message object of type 'MoveToPoseFeedback"
  "action_server/MoveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToPoseFeedback>)))
  "Returns md5sum for a message object of type '<MoveToPoseFeedback>"
  "d90953f904aa7b8e8d8b4f90a196f18f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToPoseFeedback)))
  "Returns md5sum for a message object of type 'MoveToPoseFeedback"
  "d90953f904aa7b8e8d8b4f90a196f18f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToPoseFeedback>)))
  "Returns full string definition for message of type '<MoveToPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback (optional)~%float32 feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToPoseFeedback)))
  "Returns full string definition for message of type 'MoveToPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback (optional)~%float32 feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToPoseFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToPoseFeedback
    (cl:cons ':feedback (feedback msg))
))
